title: <span style="color:DodgerBlue">Marius Radean</span>
logo: /assets/img/logo.png
description: Welcome to my personal webpage!
show_downloads: false
google_analytics: G-PLZ3B9S9GT
theme: jekyll-theme-minimal
